environment:
  global:
    TEST: -v --durations 25
    PYTHONFAULTHANDLER: x
    PYTHONWARNINGS: all

  matrix:
    - PYTHON: 27
      TEST_IGNORE: --ignore py35
    - PYTHON: 36
    - PYTHON: 36-x64

install:
  - C:\Python%PYTHON%\python.exe -m pip install -U pip setuptools
  - C:\Python%PYTHON%\python.exe -m pip install .[test,websupport]

# No automatic build, just run python tests
build: off

# Update build information before testing, no warnings during this step
before_test:
  - ps: |
      $py_warnings = $env:PYTHONWARNINGS
      $env:PYTHONWARNINGS = 'ignore'
      Update-AppveyorBuild -Version ((& "C:\Python$($env:PYTHON)\python.exe" -m sphinx --version).Split(' ')[2])
      $env:PYTHONWARNINGS = $py_warnings

test_script:
  - ps: |
      Push-Location tests
      $test_ignore = $env:TEST_IGNORE
      if (-not $test_ignore) { $test_ignore = '' }
      $tests = $env:TEST
      if (-not $tests) { $tests = '' }
      & "C:\Python$($env:PYTHON)\python.exe" -m pytest $test_ignore.Split(' ') --junitxml .junit.xml $tests.Split(' ')
      Pop-Location
      if ($LastExitCode -eq 1) { Write-Host "Test Failures Occurred, leaving for test result parsing" }
      elseif ($LastExitCode -ne 0) { Write-Host "Other Error Occurred, aborting"; exit $LastExitCode }

after_test:
  - ps: (New-Object System.Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path (Join-Path tests .junit.xml)))
